version: 0.1.{build}
image:
  - Ubuntu1804
  - Visual Studio 2017
install:
  - sh: ./setup.sh
  - cmd: ./setup.bat
build_script:
  - sh: >-
      cmake .

      make
  - cmd: >-
      cmake -A x64 .

      msbuild ./GCDecompiler.sln
test_script:
  - sh: ./test_gcd
  - cmd: ./Debug/test_gcd.exe
artifacts:
  - path: '*gcd'
    name: Ubuntu Executables
  - path: 'Debug/*.exe'
    name: Windows Executables
notifications:
  - provider: Email
    to:
      - runetynan@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
